[package]
name = "nature_common"
version = "0.1.0"
authors = ["xuebin.Li <llxxbb@yeah.net>"]

[dependencies]

serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
itertools = "0.8"

chrono = { version = "0.4", features = ["serde"] }

uuid = { version = "0.7", features = ["v3"] }


# log
log = "0.4.1"
fern = "0.5"        # Simple, efficient logging

# test
[dev-dependencies]
mockers_derive = "0.13"
mockers = "0.13"

